# ==============================
# PROFIL PRODUCTION (application-prod.properties)
# ==============================

# Logs plus restreints en prod
logging.level.root=INFO
logging.level.pressing.app=INFO
logging.level.org.hibernate.SQL=ERROR

# SQLite fichier de production
spring.datasource.url=jdbc:sqlite:./pressing-prod.db

# Pas d'affichage SQL en console
spring.jpa.show-sql=false

# Cache Thymeleaf active pour les performances
spring.thymeleaf.cache=true

# Sécurité : HTTPS requis (si derriere un proxy)
# server.forward-headers-strategy=native
