# ==============================
# PROFIL DEVELOPPEMENT (application-dev.properties)
# ==============================

# Logs plus verbeux en dev
logging.level.pressing.app=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# SQLite en mode memoire ou fichier local specifique au dev
spring.datasource.url=jdbc:sqlite:./pressing-dev.db

# Affichage du SQL formate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
